task5

CREATE TABLE CUSTOMER(name VARCHAR(30)NOT NULL, id INTEGER(4)NOT NULL);
INSERT INTO CUSTOMER VALUES('Jimmy', 1234);
INSERT INTO CUSTOMER VALUES('Mary',456);
COMMIT;
SELECT*,NOW()
FROM CUSTOMER;

